--DROP TABLE IF EXISTS MEMBER;
--CREATE TABLE MEMBER
--(
--    id VARCHAR(255) NOT NULL,
--    pw VARCHAR(255) NOT NULL,
--    fullNAme VARCHAR(255),
--    email VARCHAR(255),
--    PRIMARY KEY (id)
--);

DROP TABLE IF EXISTS MEMBER;
CREATE TABLE MEMBER (
    id VARCHAR(255) NOT NULL,
    pw VARCHAR(255) NOT NULL,
    fullNAme VARCHAR(255),
    email VARCHAR(255),
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS ROLES;
CREATE TABLE ROLES (
    id VARCHAR(50),
    role VARCHAR(50),
    PRIMARY KEY (id, role),
    UNIQUE (id, role),
    FOREIGN KEY (id) REFERENCES MEMBER(id)
);